// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package api

import (
	"context"
	"fmt"
	"net/http"
	"time"

	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "bearerAuth.Scopes"
)

// Defines values for HealthStatusStatus.
const (
	Ok HealthStatusStatus = "ok"
)

// Defines values for OAuthTokenRequestGrantType.
const (
	AuthorizationCode OAuthTokenRequestGrantType = "authorization_code"
)

// Defines values for OAuthTokenResponseTokenType.
const (
	OAuthTokenResponseTokenTypeBearer OAuthTokenResponseTokenType = "Bearer"
)

// Defines values for ReadinessStatusChecksStatus.
const (
	Down ReadinessStatusChecksStatus = "down"
	Up   ReadinessStatusChecksStatus = "up"
)

// Defines values for ReadinessStatusStatus.
const (
	Degraded ReadinessStatusStatus = "degraded"
	Ready    ReadinessStatusStatus = "ready"
)

// Defines values for TokenPairTokenType.
const (
	TokenPairTokenTypeBearer TokenPairTokenType = "Bearer"
)

// Defines values for UserStatus.
const (
	Active              UserStatus = "active"
	Disabled            UserStatus = "disabled"
	Locked              UserStatus = "locked"
	PendingVerification UserStatus = "pending_verification"
)

// Defines values for AuthorizeClientParamsResponseType.
const (
	Code AuthorizeClientParamsResponseType = "code"
)

// Defines values for AuthorizeClientParamsCodeChallengeMethod.
const (
	S256 AuthorizeClientParamsCodeChallengeMethod = "S256"
)

// AdminCreateUserRequest defines model for AdminCreateUserRequest.
type AdminCreateUserRequest struct {
	DisplayName string              `json:"displayName"`
	Email       openapi_types.Email `json:"email"`
	Roles       []Role              `json:"roles"`
}

// AdminUpdateUserRequest defines model for AdminUpdateUserRequest.
type AdminUpdateUserRequest struct {
	Roles  *[]Role     `json:"roles,omitempty"`
	Status *UserStatus `json:"status,omitempty"`
}

// Application defines model for Application.
type Application struct {
	ClientId    string             `json:"clientId"`
	Id          openapi_types.UUID `json:"id"`
	Name        string             `json:"name"`
	Permissions []Permission       `json:"permissions"`
	Roles       []ApplicationRole  `json:"roles"`
}

// ApplicationRole defines model for ApplicationRole.
type ApplicationRole struct {
	ApplicationId openapi_types.UUID `json:"applicationId"`

	// AssignedCount Usuarios que tienen asignado el rol.
	AssignedCount int                `json:"assignedCount"`
	Description   string             `json:"description"`
	Id            openapi_types.UUID `json:"id"`

	// Name Rol configurable exclusivo de una aplicación, con la forma `<client_id>.<nombre>`. El patrón solo
	// comprueba esa forma genérica; el servidor exige además que el prefijo sea exactamente el client_id
	// de la aplicación y que el nombre cumpla `^[a-z0-9][a-z0-9_-]{1,40}$`.
	Name           ApplicationRoleName `json:"name"`
	PermissionKeys []string            `json:"permissionKeys"`
	System         bool                `json:"system"`
}

// ApplicationRoleName Rol configurable exclusivo de una aplicación, con la forma `<client_id>.<nombre>`. El patrón solo
// comprueba esa forma genérica; el servidor exige además que el prefijo sea exactamente el client_id
// de la aplicación y que el nombre cumpla `^[a-z0-9][a-z0-9_-]{1,40}$`.
type ApplicationRoleName = string

// AuditEvent defines model for AuditEvent.
type AuditEvent struct {
	Action       string                  `json:"action"`
	ActorUserId  *openapi_types.UUID     `json:"actorUserId"`
	CreatedAt    time.Time               `json:"createdAt"`
	Id           int64                   `json:"id"`
	Ip           *string                 `json:"ip"`
	Metadata     *map[string]interface{} `json:"metadata,omitempty"`
	ResourceId   *string                 `json:"resourceId"`
	ResourceType *string                 `json:"resourceType"`
	UserAgent    *string                 `json:"userAgent"`
}

// AuditLogPage defines model for AuditLogPage.
type AuditLogPage struct {
	Items      []AuditEvent `json:"items"`
	NextCursor *string      `json:"nextCursor"`
}

// CreateApplicationRoleRequest defines model for CreateApplicationRoleRequest.
type CreateApplicationRoleRequest struct {
	Description *string `json:"description,omitempty"`

	// Name El prefijo debe ser igual al client_id de la aplicación (`<client_id>.<nombre>`) y el nombre cumple `^[a-z0-9][a-z0-9_-]{1,40}$`; de lo contrario, 400.
	Name           ApplicationRoleName `json:"name"`
	PermissionKeys []string            `json:"permissionKeys"`
}

// EmailRequest defines model for EmailRequest.
type EmailRequest struct {
	Email openapi_types.Email `json:"email"`
}

// HealthStatus defines model for HealthStatus.
type HealthStatus struct {
	Status  HealthStatusStatus `json:"status"`
	Version string             `json:"version"`
}

// HealthStatusStatus defines model for HealthStatus.Status.
type HealthStatusStatus string

// InvitationAcceptRequest defines model for InvitationAcceptRequest.
type InvitationAcceptRequest struct {
	Password string `json:"password"`
	Token    string `json:"token"`
}

// Jwks defines model for Jwks.
type Jwks struct {
	Keys []struct {
		Alg string `json:"alg"`
		Crv string `json:"crv"`
		Kid string `json:"kid"`
		Kty string `json:"kty"`
		Use string `json:"use"`

		// X Clave pública en base64url
		X string `json:"x"`
	} `json:"keys"`
}

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Email    openapi_types.Email `json:"email"`
	Password string              `json:"password"`
}

// MfaChallenge defines model for MfaChallenge.
type MfaChallenge struct {
	ExpiresIn int `json:"expiresIn"`

	// MfaToken Token de un solo uso, vigente 5 minutos
	MfaToken string `json:"mfaToken"`
}

// MfaResendRequest defines model for MfaResendRequest.
type MfaResendRequest struct {
	MfaToken string `json:"mfaToken"`
}

// MfaVerifyRequest defines model for MfaVerifyRequest.
type MfaVerifyRequest struct {
	// Code Código de un solo uso enviado por correo
	Code     string `json:"code"`
	MfaToken string `json:"mfaToken"`
}

// OAuthTokenRequest defines model for OAuthTokenRequest.
type OAuthTokenRequest struct {
	ClientId     string                     `json:"client_id"`
	Code         string                     `json:"code"`
	CodeVerifier string                     `json:"code_verifier"`
	GrantType    OAuthTokenRequestGrantType `json:"grant_type"`
	RedirectUri  string                     `json:"redirect_uri"`
}

// OAuthTokenRequestGrantType defines model for OAuthTokenRequest.GrantType.
type OAuthTokenRequestGrantType string

// OAuthTokenResponse defines model for OAuthTokenResponse.
type OAuthTokenResponse struct {
	// AccessToken JWT Ed25519 con `aud` del cliente y solo sus roles
	AccessToken string                      `json:"access_token"`
	ExpiresIn   int                         `json:"expires_in"`
	TokenType   OAuthTokenResponseTokenType `json:"token_type"`
}

// OAuthTokenResponseTokenType defines model for OAuthTokenResponse.TokenType.
type OAuthTokenResponseTokenType string

// PasswordResetConfirmRequest defines model for PasswordResetConfirmRequest.
type PasswordResetConfirmRequest struct {
	Password string `json:"password"`
	Token    string `json:"token"`
}

// Permission defines model for Permission.
type Permission struct {
	Description string `json:"description"`
	Key         string `json:"key"`
}

// Problem Error en formato RFC 7807. Nunca revela si un correo está registrado.
type Problem struct {
	Detail *string `json:"detail,omitempty"`

	// Errors Detalle por campo en errores de validación
	Errors *[]struct {
		Field   string `json:"field"`
		Message string `json:"message"`
	} `json:"errors,omitempty"`
	Instance *string `json:"instance,omitempty"`
	Status   int     `json:"status"`
	Title    string  `json:"title"`
	Type     string  `json:"type"`
}

// ReadinessStatus defines model for ReadinessStatus.
type ReadinessStatus struct {
	Checks map[string]struct {
		Error  *string                     `json:"error,omitempty"`
		Status ReadinessStatusChecksStatus `json:"status"`
	} `json:"checks"`
	Status ReadinessStatusStatus `json:"status"`
}

// ReadinessStatusChecksStatus defines model for ReadinessStatus.Checks.Status.
type ReadinessStatusChecksStatus string

// ReadinessStatusStatus defines model for ReadinessStatus.Status.
type ReadinessStatusStatus string

// Role Rol de directorio (`admin` o `user`) o rol configurable `<aplicacion>.<nombre>`.
type Role = string

// Session defines model for Session.
type Session struct {
	CreatedAt time.Time `json:"createdAt"`

	// Current Indica si es la sesión desde la que se consulta
	Current    bool               `json:"current"`
	Id         openapi_types.UUID `json:"id"`
	Ip         string             `json:"ip"`
	LastUsedAt time.Time          `json:"lastUsedAt"`
	UserAgent  string             `json:"userAgent"`
}

// TokenPair defines model for TokenPair.
type TokenPair struct {
	// AccessToken JWT Ed25519
	AccessToken string `json:"accessToken"`

	// ExpiresIn Segundos de vigencia del access token
	ExpiresIn int                `json:"expiresIn"`
	TokenType TokenPairTokenType `json:"tokenType"`
}

// TokenPairTokenType defines model for TokenPair.TokenType.
type TokenPairTokenType string

// TokenRequest defines model for TokenRequest.
type TokenRequest struct {
	Token string `json:"token"`
}

// UpdateApplicationRoleRequest El nombre de un rol no se puede cambiar; solo descripción y permisos.
type UpdateApplicationRoleRequest struct {
	Description    *string   `json:"description,omitempty"`
	PermissionKeys *[]string `json:"permissionKeys,omitempty"`
}

// UpdateProfileRequest defines model for UpdateProfileRequest.
type UpdateProfileRequest struct {
	DisplayName *string `json:"displayName,omitempty"`
}

// User defines model for User.
type User struct {
	CreatedAt   time.Time           `json:"createdAt"`
	DisplayName string              `json:"displayName"`
	Email       openapi_types.Email `json:"email"`
	Id          openapi_types.UUID  `json:"id"`
	LastLoginAt *time.Time          `json:"lastLoginAt"`

	// MfaEnabled Siempre verdadero para cuentas activas; no requiere enrolamiento
	MfaEnabled bool       `json:"mfaEnabled"`
	Roles      []Role     `json:"roles"`
	Status     UserStatus `json:"status"`
}

// UserPage defines model for UserPage.
type UserPage struct {
	Items      []User  `json:"items"`
	NextCursor *string `json:"nextCursor"`
}

// UserStatus defines model for UserStatus.
type UserStatus string

// Action defines model for Action.
type Action = string

// ActorId defines model for ActorId.
type ActorId = openapi_types.UUID

// ApplicationId defines model for ApplicationId.
type ApplicationId = openapi_types.UUID

// Cursor defines model for Cursor.
type Cursor = string

// Limit defines model for Limit.
type Limit = int

// Query defines model for Query.
type Query = string

// RoleId defines model for RoleId.
type RoleId = openapi_types.UUID

// SessionId defines model for SessionId.
type SessionId = openapi_types.UUID

// Since defines model for Since.
type Since = time.Time

// Status defines model for Status.
type Status = UserStatus

// UserId defines model for UserId.
type UserId = openapi_types.UUID

// BadRequest Error en formato RFC 7807. Nunca revela si un correo está registrado.
type BadRequest = Problem

// Forbidden Error en formato RFC 7807. Nunca revela si un correo está registrado.
type Forbidden = Problem

// NotFound Error en formato RFC 7807. Nunca revela si un correo está registrado.
type NotFound = Problem

// TooManyRequests Error en formato RFC 7807. Nunca revela si un correo está registrado.
type TooManyRequests = Problem

// Unauthorized Error en formato RFC 7807. Nunca revela si un correo está registrado.
type Unauthorized = Problem

// ListAuditLogParams defines parameters for ListAuditLog.
type ListAuditLogParams struct {
	Action  *Action  `form:"action,omitempty" json:"action,omitempty"`
	ActorId *ActorId `form:"actorId,omitempty" json:"actorId,omitempty"`
	Since   *Since   `form:"since,omitempty" json:"since,omitempty"`
	Limit   *Limit   `form:"limit,omitempty" json:"limit,omitempty"`
	Cursor  *Cursor  `form:"cursor,omitempty" json:"cursor,omitempty"`
}

// ListUsersParams defines parameters for ListUsers.
type ListUsersParams struct {
	// Q Búsqueda parcial por correo o nombre
	Q      *Query  `form:"q,omitempty" json:"q,omitempty"`
	Status *Status `form:"status,omitempty" json:"status,omitempty"`
	Limit  *Limit  `form:"limit,omitempty" json:"limit,omitempty"`
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`
}

// LogoutParams defines parameters for Logout.
type LogoutParams struct {
	// RefreshToken Refresh token opaco de la sesión actual.
	RefreshToken string `form:"refresh_token" json:"refresh_token"`
}

// RefreshSessionParams defines parameters for RefreshSession.
type RefreshSessionParams struct {
	// RefreshToken Refresh token opaco de la sesión actual.
	RefreshToken string `form:"refresh_token" json:"refresh_token"`
}

// AuthorizeClientParams defines parameters for AuthorizeClient.
type AuthorizeClientParams struct {
	ClientId            string                                   `form:"client_id" json:"client_id"`
	RedirectUri         string                                   `form:"redirect_uri" json:"redirect_uri"`
	ResponseType        AuthorizeClientParamsResponseType        `form:"response_type" json:"response_type"`
	State               string                                   `form:"state" json:"state"`
	CodeChallenge       string                                   `form:"code_challenge" json:"code_challenge"`
	CodeChallengeMethod AuthorizeClientParamsCodeChallengeMethod `form:"code_challenge_method" json:"code_challenge_method"`
}

// AuthorizeClientParamsResponseType defines parameters for AuthorizeClient.
type AuthorizeClientParamsResponseType string

// AuthorizeClientParamsCodeChallengeMethod defines parameters for AuthorizeClient.
type AuthorizeClientParamsCodeChallengeMethod string

// CreateApplicationRoleJSONRequestBody defines body for CreateApplicationRole for application/json ContentType.
type CreateApplicationRoleJSONRequestBody = CreateApplicationRoleRequest

// UpdateApplicationRoleJSONRequestBody defines body for UpdateApplicationRole for application/json ContentType.
type UpdateApplicationRoleJSONRequestBody = UpdateApplicationRoleRequest

// CreateEmployeeJSONRequestBody defines body for CreateEmployee for application/json ContentType.
type CreateEmployeeJSONRequestBody = AdminCreateUserRequest

// UpdateUserJSONRequestBody defines body for UpdateUser for application/json ContentType.
type UpdateUserJSONRequestBody = AdminUpdateUserRequest

// AcceptInvitationJSONRequestBody defines body for AcceptInvitation for application/json ContentType.
type AcceptInvitationJSONRequestBody = InvitationAcceptRequest

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = LoginRequest

// ResendMfaCodeJSONRequestBody defines body for ResendMfaCode for application/json ContentType.
type ResendMfaCodeJSONRequestBody = MfaResendRequest

// VerifyMfaJSONRequestBody defines body for VerifyMfa for application/json ContentType.
type VerifyMfaJSONRequestBody = MfaVerifyRequest

// ConfirmPasswordResetJSONRequestBody defines body for ConfirmPasswordReset for application/json ContentType.
type ConfirmPasswordResetJSONRequestBody = PasswordResetConfirmRequest

// RequestPasswordResetJSONRequestBody defines body for RequestPasswordReset for application/json ContentType.
type RequestPasswordResetJSONRequestBody = EmailRequest

// UpdateCurrentUserJSONRequestBody defines body for UpdateCurrentUser for application/json ContentType.
type UpdateCurrentUserJSONRequestBody = UpdateProfileRequest

// ExchangeAuthorizationCodeFormdataRequestBody defines body for ExchangeAuthorizationCode for application/x-www-form-urlencoded ContentType.
type ExchangeAuthorizationCodeFormdataRequestBody = OAuthTokenRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Clave pública para validar los tokens emitidos
	// (GET /.well-known/jwks.json)
	GetJwks(w http.ResponseWriter, r *http.Request)
	// Listar aplicaciones, permisos y roles configurables
	// (GET /api/v1/admin/applications)
	ListApplications(w http.ResponseWriter, r *http.Request)

	// (GET /api/v1/admin/applications/{applicationId}/roles)
	ListApplicationRoles(w http.ResponseWriter, r *http.Request, applicationId ApplicationId)

	// (POST /api/v1/admin/applications/{applicationId}/roles)
	CreateApplicationRole(w http.ResponseWriter, r *http.Request, applicationId ApplicationId)
	// Eliminar un rol de aplicación sin asignaciones
	// (DELETE /api/v1/admin/applications/{applicationId}/roles/{roleId})
	DeleteApplicationRole(w http.ResponseWriter, r *http.Request, applicationId ApplicationId, roleId RoleId)
	// Actualizar descripción o permisos de un rol (no admite renombrar)
	// (PATCH /api/v1/admin/applications/{applicationId}/roles/{roleId})
	UpdateApplicationRole(w http.ResponseWriter, r *http.Request, applicationId ApplicationId, roleId RoleId)
	// Consultar el registro de auditoría
	// (GET /api/v1/admin/audit-log)
	ListAuditLog(w http.ResponseWriter, r *http.Request, params ListAuditLogParams)
	// Listar y buscar cuentas
	// (GET /api/v1/admin/users)
	ListUsers(w http.ResponseWriter, r *http.Request, params ListUsersParams)
	// Dar de alta a un empleado y enviar su invitación
	// (POST /api/v1/admin/users)
	CreateEmployee(w http.ResponseWriter, r *http.Request)
	// Consultar una cuenta
	// (GET /api/v1/admin/users/{userId})
	GetUser(w http.ResponseWriter, r *http.Request, userId UserId)
	// Cambiar el estado o los roles de una cuenta
	// (PATCH /api/v1/admin/users/{userId})
	UpdateUser(w http.ResponseWriter, r *http.Request, userId UserId)
	// Reenviar la invitación de una cuenta pendiente
	// (POST /api/v1/admin/users/{userId}/invitation)
	ResendInvitation(w http.ResponseWriter, r *http.Request, userId UserId)
	// Aceptar una invitación y definir la contraseña
	// (POST /api/v1/auth/invitations/accept)
	AcceptInvitation(w http.ResponseWriter, r *http.Request)
	// Iniciar sesión con correo y contraseña
	// (POST /api/v1/auth/login)
	Login(w http.ResponseWriter, r *http.Request)
	// Revocar el refresh token de la sesión actual
	// (POST /api/v1/auth/logout)
	Logout(w http.ResponseWriter, r *http.Request, params LogoutParams)
	// Reenviar el código del desafío MFA
	// (POST /api/v1/auth/mfa/resend)
	ResendMfaCode(w http.ResponseWriter, r *http.Request)
	// Canjear el desafío de segundo factor por una sesión
	// (POST /api/v1/auth/mfa/verify)
	VerifyMfa(w http.ResponseWriter, r *http.Request)
	// Fijar una contraseña nueva con el token recibido
	// (POST /api/v1/auth/password-reset/confirm)
	ConfirmPasswordReset(w http.ResponseWriter, r *http.Request)
	// Solicitar un enlace de restablecimiento
	// (POST /api/v1/auth/password-reset/request)
	RequestPasswordReset(w http.ResponseWriter, r *http.Request)
	// Rotar el refresh token y obtener un par nuevo
	// (POST /api/v1/auth/refresh)
	RefreshSession(w http.ResponseWriter, r *http.Request, params RefreshSessionParams)
	// Perfil del usuario autenticado
	// (GET /api/v1/me)
	GetCurrentUser(w http.ResponseWriter, r *http.Request)
	// Actualizar el perfil propio
	// (PATCH /api/v1/me)
	UpdateCurrentUser(w http.ResponseWriter, r *http.Request)
	// Sesiones activas del titular
	// (GET /api/v1/me/sessions)
	ListSessions(w http.ResponseWriter, r *http.Request)
	// Revocar una sesión concreta
	// (DELETE /api/v1/me/sessions/{sessionId})
	RevokeSession(w http.ResponseWriter, r *http.Request, sessionId SessionId)
	// Sonda de vitalidad
	// (GET /healthz)
	GetHealth(w http.ResponseWriter, r *http.Request)
	// Autorizar al cliente mediante Authorization Code con PKCE
	// (GET /oauth/authorize)
	AuthorizeClient(w http.ResponseWriter, r *http.Request, params AuthorizeClientParams)
	// Canjear un código de autorización por un access token
	// (POST /oauth/token)
	ExchangeAuthorizationCode(w http.ResponseWriter, r *http.Request)
	// Sonda de disponibilidad (comprueba base de datos y broker)
	// (GET /readyz)
	GetReadiness(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Clave pública para validar los tokens emitidos
// (GET /.well-known/jwks.json)
func (_ Unimplemented) GetJwks(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Listar aplicaciones, permisos y roles configurables
// (GET /api/v1/admin/applications)
func (_ Unimplemented) ListApplications(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /api/v1/admin/applications/{applicationId}/roles)
func (_ Unimplemented) ListApplicationRoles(w http.ResponseWriter, r *http.Request, applicationId ApplicationId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /api/v1/admin/applications/{applicationId}/roles)
func (_ Unimplemented) CreateApplicationRole(w http.ResponseWriter, r *http.Request, applicationId ApplicationId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Eliminar un rol de aplicación sin asignaciones
// (DELETE /api/v1/admin/applications/{applicationId}/roles/{roleId})
func (_ Unimplemented) DeleteApplicationRole(w http.ResponseWriter, r *http.Request, applicationId ApplicationId, roleId RoleId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Actualizar descripción o permisos de un rol (no admite renombrar)
// (PATCH /api/v1/admin/applications/{applicationId}/roles/{roleId})
func (_ Unimplemented) UpdateApplicationRole(w http.ResponseWriter, r *http.Request, applicationId ApplicationId, roleId RoleId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Consultar el registro de auditoría
// (GET /api/v1/admin/audit-log)
func (_ Unimplemented) ListAuditLog(w http.ResponseWriter, r *http.Request, params ListAuditLogParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Listar y buscar cuentas
// (GET /api/v1/admin/users)
func (_ Unimplemented) ListUsers(w http.ResponseWriter, r *http.Request, params ListUsersParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Dar de alta a un empleado y enviar su invitación
// (POST /api/v1/admin/users)
func (_ Unimplemented) CreateEmployee(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Consultar una cuenta
// (GET /api/v1/admin/users/{userId})
func (_ Unimplemented) GetUser(w http.ResponseWriter, r *http.Request, userId UserId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Cambiar el estado o los roles de una cuenta
// (PATCH /api/v1/admin/users/{userId})
func (_ Unimplemented) UpdateUser(w http.ResponseWriter, r *http.Request, userId UserId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Reenviar la invitación de una cuenta pendiente
// (POST /api/v1/admin/users/{userId}/invitation)
func (_ Unimplemented) ResendInvitation(w http.ResponseWriter, r *http.Request, userId UserId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Aceptar una invitación y definir la contraseña
// (POST /api/v1/auth/invitations/accept)
func (_ Unimplemented) AcceptInvitation(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Iniciar sesión con correo y contraseña
// (POST /api/v1/auth/login)
func (_ Unimplemented) Login(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Revocar el refresh token de la sesión actual
// (POST /api/v1/auth/logout)
func (_ Unimplemented) Logout(w http.ResponseWriter, r *http.Request, params LogoutParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Reenviar el código del desafío MFA
// (POST /api/v1/auth/mfa/resend)
func (_ Unimplemented) ResendMfaCode(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Canjear el desafío de segundo factor por una sesión
// (POST /api/v1/auth/mfa/verify)
func (_ Unimplemented) VerifyMfa(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Fijar una contraseña nueva con el token recibido
// (POST /api/v1/auth/password-reset/confirm)
func (_ Unimplemented) ConfirmPasswordReset(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Solicitar un enlace de restablecimiento
// (POST /api/v1/auth/password-reset/request)
func (_ Unimplemented) RequestPasswordReset(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Rotar el refresh token y obtener un par nuevo
// (POST /api/v1/auth/refresh)
func (_ Unimplemented) RefreshSession(w http.ResponseWriter, r *http.Request, params RefreshSessionParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Perfil del usuario autenticado
// (GET /api/v1/me)
func (_ Unimplemented) GetCurrentUser(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Actualizar el perfil propio
// (PATCH /api/v1/me)
func (_ Unimplemented) UpdateCurrentUser(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Sesiones activas del titular
// (GET /api/v1/me/sessions)
func (_ Unimplemented) ListSessions(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Revocar una sesión concreta
// (DELETE /api/v1/me/sessions/{sessionId})
func (_ Unimplemented) RevokeSession(w http.ResponseWriter, r *http.Request, sessionId SessionId) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Sonda de vitalidad
// (GET /healthz)
func (_ Unimplemented) GetHealth(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Autorizar al cliente mediante Authorization Code con PKCE
// (GET /oauth/authorize)
func (_ Unimplemented) AuthorizeClient(w http.ResponseWriter, r *http.Request, params AuthorizeClientParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Canjear un código de autorización por un access token
// (POST /oauth/token)
func (_ Unimplemented) ExchangeAuthorizationCode(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Sonda de disponibilidad (comprueba base de datos y broker)
// (GET /readyz)
func (_ Unimplemented) GetReadiness(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// GetJwks operation middleware
func (siw *ServerInterfaceWrapper) GetJwks(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetJwks(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListApplications operation middleware
func (siw *ServerInterfaceWrapper) ListApplications(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListApplications(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListApplicationRoles operation middleware
func (siw *ServerInterfaceWrapper) ListApplicationRoles(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "applicationId" -------------
	var applicationId ApplicationId

	err = runtime.BindStyledParameterWithOptions("simple", "applicationId", chi.URLParam(r, "applicationId"), &applicationId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "applicationId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListApplicationRoles(w, r, applicationId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateApplicationRole operation middleware
func (siw *ServerInterfaceWrapper) CreateApplicationRole(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "applicationId" -------------
	var applicationId ApplicationId

	err = runtime.BindStyledParameterWithOptions("simple", "applicationId", chi.URLParam(r, "applicationId"), &applicationId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "applicationId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateApplicationRole(w, r, applicationId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteApplicationRole operation middleware
func (siw *ServerInterfaceWrapper) DeleteApplicationRole(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "applicationId" -------------
	var applicationId ApplicationId

	err = runtime.BindStyledParameterWithOptions("simple", "applicationId", chi.URLParam(r, "applicationId"), &applicationId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "applicationId", Err: err})
		return
	}

	// ------------- Path parameter "roleId" -------------
	var roleId RoleId

	err = runtime.BindStyledParameterWithOptions("simple", "roleId", chi.URLParam(r, "roleId"), &roleId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "roleId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteApplicationRole(w, r, applicationId, roleId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateApplicationRole operation middleware
func (siw *ServerInterfaceWrapper) UpdateApplicationRole(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "applicationId" -------------
	var applicationId ApplicationId

	err = runtime.BindStyledParameterWithOptions("simple", "applicationId", chi.URLParam(r, "applicationId"), &applicationId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "applicationId", Err: err})
		return
	}

	// ------------- Path parameter "roleId" -------------
	var roleId RoleId

	err = runtime.BindStyledParameterWithOptions("simple", "roleId", chi.URLParam(r, "roleId"), &roleId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "roleId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateApplicationRole(w, r, applicationId, roleId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListAuditLog operation middleware
func (siw *ServerInterfaceWrapper) ListAuditLog(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListAuditLogParams

	// ------------- Optional query parameter "action" -------------

	err = runtime.BindQueryParameter("form", true, false, "action", r.URL.Query(), &params.Action)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "action", Err: err})
		return
	}

	// ------------- Optional query parameter "actorId" -------------

	err = runtime.BindQueryParameter("form", true, false, "actorId", r.URL.Query(), &params.ActorId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "actorId", Err: err})
		return
	}

	// ------------- Optional query parameter "since" -------------

	err = runtime.BindQueryParameter("form", true, false, "since", r.URL.Query(), &params.Since)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "since", Err: err})
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameter("form", true, false, "cursor", r.URL.Query(), &params.Cursor)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cursor", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListAuditLog(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListUsers operation middleware
func (siw *ServerInterfaceWrapper) ListUsers(w http.ResponseWriter, r *http.Request) {

	var err error

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListUsersParams

	// ------------- Optional query parameter "q" -------------

	err = runtime.BindQueryParameter("form", true, false, "q", r.URL.Query(), &params.Q)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "q", Err: err})
		return
	}

	// ------------- Optional query parameter "status" -------------

	err = runtime.BindQueryParameter("form", true, false, "status", r.URL.Query(), &params.Status)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "status", Err: err})
		return
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", r.URL.Query(), &params.Limit)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		return
	}

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameter("form", true, false, "cursor", r.URL.Query(), &params.Cursor)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cursor", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListUsers(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateEmployee operation middleware
func (siw *ServerInterfaceWrapper) CreateEmployee(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateEmployee(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetUser operation middleware
func (siw *ServerInterfaceWrapper) GetUser(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "userId" -------------
	var userId UserId

	err = runtime.BindStyledParameterWithOptions("simple", "userId", chi.URLParam(r, "userId"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "userId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetUser(w, r, userId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateUser operation middleware
func (siw *ServerInterfaceWrapper) UpdateUser(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "userId" -------------
	var userId UserId

	err = runtime.BindStyledParameterWithOptions("simple", "userId", chi.URLParam(r, "userId"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "userId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateUser(w, r, userId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ResendInvitation operation middleware
func (siw *ServerInterfaceWrapper) ResendInvitation(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "userId" -------------
	var userId UserId

	err = runtime.BindStyledParameterWithOptions("simple", "userId", chi.URLParam(r, "userId"), &userId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "userId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ResendInvitation(w, r, userId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AcceptInvitation operation middleware
func (siw *ServerInterfaceWrapper) AcceptInvitation(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AcceptInvitation(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Login operation middleware
func (siw *ServerInterfaceWrapper) Login(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Login(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Logout operation middleware
func (siw *ServerInterfaceWrapper) Logout(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params LogoutParams

	{
		var cookie *http.Cookie

		if cookie, err = r.Cookie("refresh_token"); err == nil {
			var value string
			err = runtime.BindStyledParameterWithOptions("simple", "refresh_token", cookie.Value, &value, runtime.BindStyledParameterOptions{Explode: true, Required: true})
			if err != nil {
				siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "refresh_token", Err: err})
				return
			}
			params.RefreshToken = value

		} else {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "refresh_token"})
			return
		}
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Logout(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ResendMfaCode operation middleware
func (siw *ServerInterfaceWrapper) ResendMfaCode(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ResendMfaCode(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// VerifyMfa operation middleware
func (siw *ServerInterfaceWrapper) VerifyMfa(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.VerifyMfa(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ConfirmPasswordReset operation middleware
func (siw *ServerInterfaceWrapper) ConfirmPasswordReset(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ConfirmPasswordReset(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RequestPasswordReset operation middleware
func (siw *ServerInterfaceWrapper) RequestPasswordReset(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RequestPasswordReset(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RefreshSession operation middleware
func (siw *ServerInterfaceWrapper) RefreshSession(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params RefreshSessionParams

	{
		var cookie *http.Cookie

		if cookie, err = r.Cookie("refresh_token"); err == nil {
			var value string
			err = runtime.BindStyledParameterWithOptions("simple", "refresh_token", cookie.Value, &value, runtime.BindStyledParameterOptions{Explode: true, Required: true})
			if err != nil {
				siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "refresh_token", Err: err})
				return
			}
			params.RefreshToken = value

		} else {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "refresh_token"})
			return
		}
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RefreshSession(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetCurrentUser operation middleware
func (siw *ServerInterfaceWrapper) GetCurrentUser(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCurrentUser(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateCurrentUser operation middleware
func (siw *ServerInterfaceWrapper) UpdateCurrentUser(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateCurrentUser(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListSessions operation middleware
func (siw *ServerInterfaceWrapper) ListSessions(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListSessions(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RevokeSession operation middleware
func (siw *ServerInterfaceWrapper) RevokeSession(w http.ResponseWriter, r *http.Request) {

	var err error

	// ------------- Path parameter "sessionId" -------------
	var sessionId SessionId

	err = runtime.BindStyledParameterWithOptions("simple", "sessionId", chi.URLParam(r, "sessionId"), &sessionId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "sessionId", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RevokeSession(w, r, sessionId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHealth operation middleware
func (siw *ServerInterfaceWrapper) GetHealth(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealth(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AuthorizeClient operation middleware
func (siw *ServerInterfaceWrapper) AuthorizeClient(w http.ResponseWriter, r *http.Request) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params AuthorizeClientParams

	// ------------- Required query parameter "client_id" -------------

	if paramValue := r.URL.Query().Get("client_id"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "client_id"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "client_id", r.URL.Query(), &params.ClientId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "client_id", Err: err})
		return
	}

	// ------------- Required query parameter "redirect_uri" -------------

	if paramValue := r.URL.Query().Get("redirect_uri"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "redirect_uri"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "redirect_uri", r.URL.Query(), &params.RedirectUri)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "redirect_uri", Err: err})
		return
	}

	// ------------- Required query parameter "response_type" -------------

	if paramValue := r.URL.Query().Get("response_type"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "response_type"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "response_type", r.URL.Query(), &params.ResponseType)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "response_type", Err: err})
		return
	}

	// ------------- Required query parameter "state" -------------

	if paramValue := r.URL.Query().Get("state"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "state"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "state", r.URL.Query(), &params.State)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "state", Err: err})
		return
	}

	// ------------- Required query parameter "code_challenge" -------------

	if paramValue := r.URL.Query().Get("code_challenge"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "code_challenge"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "code_challenge", r.URL.Query(), &params.CodeChallenge)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "code_challenge", Err: err})
		return
	}

	// ------------- Required query parameter "code_challenge_method" -------------

	if paramValue := r.URL.Query().Get("code_challenge_method"); paramValue != "" {

	} else {
		siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "code_challenge_method"})
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "code_challenge_method", r.URL.Query(), &params.CodeChallengeMethod)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "code_challenge_method", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AuthorizeClient(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ExchangeAuthorizationCode operation middleware
func (siw *ServerInterfaceWrapper) ExchangeAuthorizationCode(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ExchangeAuthorizationCode(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetReadiness operation middleware
func (siw *ServerInterfaceWrapper) GetReadiness(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetReadiness(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/.well-known/jwks.json", wrapper.GetJwks)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/admin/applications", wrapper.ListApplications)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/admin/applications/{applicationId}/roles", wrapper.ListApplicationRoles)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/admin/applications/{applicationId}/roles", wrapper.CreateApplicationRole)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/api/v1/admin/applications/{applicationId}/roles/{roleId}", wrapper.DeleteApplicationRole)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/api/v1/admin/applications/{applicationId}/roles/{roleId}", wrapper.UpdateApplicationRole)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/admin/audit-log", wrapper.ListAuditLog)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/admin/users", wrapper.ListUsers)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/admin/users", wrapper.CreateEmployee)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/admin/users/{userId}", wrapper.GetUser)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/api/v1/admin/users/{userId}", wrapper.UpdateUser)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/admin/users/{userId}/invitation", wrapper.ResendInvitation)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/auth/invitations/accept", wrapper.AcceptInvitation)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/auth/login", wrapper.Login)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/auth/logout", wrapper.Logout)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/auth/mfa/resend", wrapper.ResendMfaCode)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/auth/mfa/verify", wrapper.VerifyMfa)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/auth/password-reset/confirm", wrapper.ConfirmPasswordReset)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/auth/password-reset/request", wrapper.RequestPasswordReset)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/v1/auth/refresh", wrapper.RefreshSession)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/me", wrapper.GetCurrentUser)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/api/v1/me", wrapper.UpdateCurrentUser)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/v1/me/sessions", wrapper.ListSessions)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/api/v1/me/sessions/{sessionId}", wrapper.RevokeSession)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/healthz", wrapper.GetHealth)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/oauth/authorize", wrapper.AuthorizeClient)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/oauth/token", wrapper.ExchangeAuthorizationCode)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/readyz", wrapper.GetReadiness)
	})

	return r
}
