// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package sqlc

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const countLoginFailuresByAccount = `-- name: CountLoginFailuresByAccount :one
SELECT count(*)::bigint
FROM audit_log
WHERE actor_user_id = $1
  AND action = 'login_failed'
  AND created_at >= $2
`

type CountLoginFailuresByAccountParams struct {
	ActorUserID pgtype.UUID
	CreatedAt   pgtype.Timestamptz
}

func (q *Queries) CountLoginFailuresByAccount(ctx context.Context, arg CountLoginFailuresByAccountParams) (int64, error) {
	row := q.db.QueryRow(ctx, countLoginFailuresByAccount, arg.ActorUserID, arg.CreatedAt)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countLoginFailuresByIP = `-- name: CountLoginFailuresByIP :one
SELECT count(*)::bigint
FROM audit_log
WHERE ip = $1
  AND action = 'login_failed'
  AND created_at >= $2
`

type CountLoginFailuresByIPParams struct {
	Ip        *netip.Addr
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) CountLoginFailuresByIP(ctx context.Context, arg CountLoginFailuresByIPParams) (int64, error) {
	row := q.db.QueryRow(ctx, countLoginFailuresByIP, arg.Ip, arg.CreatedAt)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const insertAuditEvent = `-- name: InsertAuditEvent :one
INSERT INTO audit_log (
    actor_user_id,
    action,
    resource_type,
    resource_id,
    ip,
    user_agent,
    metadata
)
VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7::jsonb
)
RETURNING id, actor_user_id, action, resource_type, resource_id, ip, user_agent, metadata, created_at
`

type InsertAuditEventParams struct {
	ActorUserID  pgtype.UUID
	Action       string
	ResourceType pgtype.Text
	ResourceID   pgtype.Text
	Ip           *netip.Addr
	UserAgent    pgtype.Text
	Metadata     []byte
}

func (q *Queries) InsertAuditEvent(ctx context.Context, arg InsertAuditEventParams) (AuditLog, error) {
	row := q.db.QueryRow(ctx, insertAuditEvent,
		arg.ActorUserID,
		arg.Action,
		arg.ResourceType,
		arg.ResourceID,
		arg.Ip,
		arg.UserAgent,
		arg.Metadata,
	)
	var i AuditLog
	err := row.Scan(
		&i.ID,
		&i.ActorUserID,
		&i.Action,
		&i.ResourceType,
		&i.ResourceID,
		&i.Ip,
		&i.UserAgent,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const listAuditLog = `-- name: ListAuditLog :many
SELECT id, actor_user_id, action, resource_type, resource_id, ip, user_agent, metadata, created_at
FROM audit_log
WHERE ($1::text IS NULL OR action = $1::text)
  AND ($2::uuid IS NULL OR actor_user_id = $2::uuid)
  AND ($3::timestamptz IS NULL OR created_at >= $3::timestamptz)
  AND ($4::bigint IS NULL OR id < $4::bigint)
ORDER BY id DESC
LIMIT $5
`

type ListAuditLogParams struct {
	Action      pgtype.Text
	ActorUserID pgtype.UUID
	Since       pgtype.Timestamptz
	CursorID    pgtype.Int8
	LimitCount  int32
}

func (q *Queries) ListAuditLog(ctx context.Context, arg ListAuditLogParams) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditLog,
		arg.Action,
		arg.ActorUserID,
		arg.Since,
		arg.CursorID,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AuditLog
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.ActorUserID,
			&i.Action,
			&i.ResourceType,
			&i.ResourceID,
			&i.Ip,
			&i.UserAgent,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
