// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: roles.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const listPermissionKeysForRolesAndApplication = `-- name: ListPermissionKeysForRolesAndApplication :many
SELECT DISTINCT permissions.key
FROM role_permissions
JOIN roles ON roles.id = role_permissions.role_id
JOIN permissions ON permissions.id = role_permissions.permission_id
JOIN applications ON applications.id = roles.application_id
WHERE roles.name = ANY($1::text[])
  AND applications.client_id = $2
  AND permissions.application_id = roles.application_id
ORDER BY permissions.key
`

type ListPermissionKeysForRolesAndApplicationParams struct {
	RoleNames []string
	ClientID  string
}

func (q *Queries) ListPermissionKeysForRolesAndApplication(ctx context.Context, arg ListPermissionKeysForRolesAndApplicationParams) ([]string, error) {
	rows, err := q.db.Query(ctx, listPermissionKeysForRolesAndApplication, arg.RoleNames, arg.ClientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var key string
		if err := rows.Scan(&key); err != nil {
			return nil, err
		}
		items = append(items, key)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRolesWithApplication = `-- name: ListRolesWithApplication :many
SELECT roles.id, roles.name, roles.description, roles.application_id, roles.system,
       applications.client_id
FROM roles
LEFT JOIN applications ON applications.id = roles.application_id
ORDER BY roles.name
`

type ListRolesWithApplicationRow struct {
	ID            uuid.UUID
	Name          string
	Description   string
	ApplicationID pgtype.UUID
	System        bool
	ClientID      pgtype.Text
}

func (q *Queries) ListRolesWithApplication(ctx context.Context) ([]ListRolesWithApplicationRow, error) {
	rows, err := q.db.Query(ctx, listRolesWithApplication)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRolesWithApplicationRow
	for rows.Next() {
		var i ListRolesWithApplicationRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.ApplicationID,
			&i.System,
			&i.ClientID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const validateRoleNames = `-- name: ValidateRoleNames :many
SELECT name
FROM roles
WHERE name = ANY($1::text[])
ORDER BY name
`

func (q *Queries) ValidateRoleNames(ctx context.Context, roleNames []string) ([]string, error) {
	rows, err := q.db.Query(ctx, validateRoleNames, roleNames)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
