// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package sqlc

import (
	"context"
	"net/netip"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const consumeEmailVerificationToken = `-- name: ConsumeEmailVerificationToken :one
WITH consumed AS (
    UPDATE verification_tokens
    SET used_at = now()
    WHERE token_hash = $1
      AND purpose = 'email_verification'
      AND used_at IS NULL
      AND expires_at > now()
    RETURNING user_id
)
UPDATE users
SET status = 'active', updated_at = now()
WHERE id = (SELECT user_id FROM consumed)
  AND status = 'pending_verification'
RETURNING id, email, password_hash, display_name, status, mfa_enabled, mfa_secret_enc, failed_login_count, locked_until, last_login_at, created_at, updated_at
`

func (q *Queries) ConsumeEmailVerificationToken(ctx context.Context, tokenHash []byte) (User, error) {
	row := q.db.QueryRow(ctx, consumeEmailVerificationToken, tokenHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.DisplayName,
		&i.Status,
		&i.MfaEnabled,
		&i.MfaSecretEnc,
		&i.FailedLoginCount,
		&i.LockedUntil,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createRefreshToken = `-- name: CreateRefreshToken :exec
INSERT INTO refresh_tokens (user_id, token_hash, family_id, ip, user_agent, expires_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateRefreshTokenParams struct {
	UserID    uuid.UUID
	TokenHash []byte
	FamilyID  uuid.UUID
	Ip        *netip.Addr
	UserAgent pgtype.Text
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) error {
	_, err := q.db.Exec(ctx, createRefreshToken,
		arg.UserID,
		arg.TokenHash,
		arg.FamilyID,
		arg.Ip,
		arg.UserAgent,
		arg.ExpiresAt,
	)
	return err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, password_hash, display_name)
VALUES ($1, $2, $3)
RETURNING id, email, password_hash, display_name, status, mfa_enabled, mfa_secret_enc, failed_login_count, locked_until, last_login_at, created_at, updated_at
`

type CreateUserParams struct {
	Email        string
	PasswordHash string
	DisplayName  string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.PasswordHash, arg.DisplayName)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.DisplayName,
		&i.Status,
		&i.MfaEnabled,
		&i.MfaSecretEnc,
		&i.FailedLoginCount,
		&i.LockedUntil,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createVerificationToken = `-- name: CreateVerificationToken :exec
INSERT INTO verification_tokens (user_id, token_hash, purpose, expires_at)
VALUES ($1, $2, 'email_verification', $3)
`

type CreateVerificationTokenParams struct {
	UserID    uuid.UUID
	TokenHash []byte
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) CreateVerificationToken(ctx context.Context, arg CreateVerificationTokenParams) error {
	_, err := q.db.Exec(ctx, createVerificationToken, arg.UserID, arg.TokenHash, arg.ExpiresAt)
	return err
}

const getLoginUserByEmail = `-- name: GetLoginUserByEmail :one
SELECT id, email, password_hash, status, mfa_enabled
FROM users
WHERE email = $1
`

type GetLoginUserByEmailRow struct {
	ID           uuid.UUID
	Email        string
	PasswordHash string
	Status       UserStatus
	MfaEnabled   bool
}

func (q *Queries) GetLoginUserByEmail(ctx context.Context, email string) (GetLoginUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getLoginUserByEmail, email)
	var i GetLoginUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Status,
		&i.MfaEnabled,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, display_name, status, mfa_enabled, mfa_secret_enc, failed_login_count, locked_until, last_login_at, created_at, updated_at
FROM users
WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.DisplayName,
		&i.Status,
		&i.MfaEnabled,
		&i.MfaSecretEnc,
		&i.FailedLoginCount,
		&i.LockedUntil,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, password_hash, display_name, status, mfa_enabled, mfa_secret_enc, failed_login_count, locked_until, last_login_at, created_at, updated_at
FROM users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.DisplayName,
		&i.Status,
		&i.MfaEnabled,
		&i.MfaSecretEnc,
		&i.FailedLoginCount,
		&i.LockedUntil,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listRolesForUser = `-- name: ListRolesForUser :many
SELECT roles.name
FROM user_roles
JOIN roles ON roles.id = user_roles.role_id
WHERE user_roles.user_id = $1
ORDER BY roles.name
`

func (q *Queries) ListRolesForUser(ctx context.Context, userID uuid.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, listRolesForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeRefreshFamily = `-- name: RevokeRefreshFamily :one
WITH revoked AS (
    UPDATE refresh_tokens
    SET status = 'revoked'
    WHERE family_id = $1
      AND status <> 'revoked'
    RETURNING 1
)
SELECT count(*)::bigint FROM revoked
`

func (q *Queries) RevokeRefreshFamily(ctx context.Context, familyID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, revokeRefreshFamily, familyID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const revokeRefreshToken = `-- name: RevokeRefreshToken :one
UPDATE refresh_tokens
SET status = 'revoked', last_used_at = now()
WHERE token_hash = $1
  AND status = 'active'
  AND expires_at > now()
RETURNING user_id
`

func (q *Queries) RevokeRefreshToken(ctx context.Context, tokenHash []byte) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, revokeRefreshToken, tokenHash)
	var user_id uuid.UUID
	err := row.Scan(&user_id)
	return user_id, err
}

const rotateRefreshToken = `-- name: RotateRefreshToken :one
WITH candidate AS (
    SELECT id, user_id, family_id, status, expires_at
    FROM refresh_tokens
    WHERE refresh_tokens.token_hash = $1
    FOR UPDATE
), rotated AS (
    UPDATE refresh_tokens
    SET status = 'rotated', last_used_at = now()
    WHERE id = (SELECT id FROM candidate)
      AND status = 'active'
      AND expires_at > now()
    RETURNING id
), created AS (
    INSERT INTO refresh_tokens (user_id, token_hash, family_id, parent_id, ip, user_agent, expires_at)
    SELECT candidate.user_id, $2, candidate.family_id, candidate.id, $3, $4, $5
    FROM candidate
    JOIN rotated ON true
    RETURNING id
)
SELECT candidate.user_id, candidate.family_id, candidate.id AS parent_id,
       candidate.status, EXISTS (SELECT 1 FROM created) AS rotated
FROM candidate
`

type RotateRefreshTokenParams struct {
	TokenHash   []byte
	TokenHash_2 []byte
	Ip          *netip.Addr
	UserAgent   pgtype.Text
	ExpiresAt   pgtype.Timestamptz
}

type RotateRefreshTokenRow struct {
	UserID   uuid.UUID
	FamilyID uuid.UUID
	ParentID uuid.UUID
	Status   RefreshStatus
	Rotated  bool
}

func (q *Queries) RotateRefreshToken(ctx context.Context, arg RotateRefreshTokenParams) (RotateRefreshTokenRow, error) {
	row := q.db.QueryRow(ctx, rotateRefreshToken,
		arg.TokenHash,
		arg.TokenHash_2,
		arg.Ip,
		arg.UserAgent,
		arg.ExpiresAt,
	)
	var i RotateRefreshTokenRow
	err := row.Scan(
		&i.UserID,
		&i.FamilyID,
		&i.ParentID,
		&i.Status,
		&i.Rotated,
	)
	return i, err
}

const updateDisplayName = `-- name: UpdateDisplayName :one
UPDATE users
SET display_name = $2
WHERE id = $1
RETURNING id, email, password_hash, display_name, status, mfa_enabled, mfa_secret_enc, failed_login_count, locked_until, last_login_at, created_at, updated_at
`

type UpdateDisplayNameParams struct {
	ID          uuid.UUID
	DisplayName string
}

func (q *Queries) UpdateDisplayName(ctx context.Context, arg UpdateDisplayNameParams) (User, error) {
	row := q.db.QueryRow(ctx, updateDisplayName, arg.ID, arg.DisplayName)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.DisplayName,
		&i.Status,
		&i.MfaEnabled,
		&i.MfaSecretEnc,
		&i.FailedLoginCount,
		&i.LockedUntil,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateLoginSuccess = `-- name: UpdateLoginSuccess :exec
UPDATE users
SET password_hash = $2,
    last_login_at = now()
WHERE id = $1
`

type UpdateLoginSuccessParams struct {
	ID           uuid.UUID
	PasswordHash string
}

func (q *Queries) UpdateLoginSuccess(ctx context.Context, arg UpdateLoginSuccessParams) error {
	_, err := q.db.Exec(ctx, updateLoginSuccess, arg.ID, arg.PasswordHash)
	return err
}
