/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Sonda de vitalidad */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Sonda de disponibilidad (comprueba base de datos y broker) */
        get: operations["getReadiness"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/.well-known/jwks.json": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Clave pública para validar los tokens emitidos
         * @description CORS sin credenciales, permitido solo al origen configurado del cliente.
         */
        get: operations["getJwks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/invitations/accept": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Aceptar una invitación y definir la contraseña
         * @description Consume un token de invitación de un solo uso y activa la cuenta.
         */
        post: operations["acceptInvitation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Iniciar sesión con correo y contraseña
         * @description Una contraseña correcta siempre devuelve `202` con un `mfaToken` temporal y
         *     envía por correo un código de 6 dígitos. No crea sesión hasta completar MFA.
         *     Cada desafío nuevo anula los abiertos de la cuenta; se emiten como máximo 5 por cuenta
         *     cada 15 minutos (`429` al superarlo). El código se publica tras confirmar la transacción:
         *     si el broker falla, responde `503` y anula ese desafío para que no consuma el límite de emisión (ADR 0006, D16).
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/mfa/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Canjear el desafío de segundo factor por una sesión */
        post: operations["verifyMfa"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/mfa/resend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reenviar el código del desafío MFA
         * @description Anula el código anterior, conserva el desafío y permite un envío cada 60 segundos. Si el broker falla después del commit, restaura el código y `lastSentAt` previos para permitir reintentar sin esperar.
         */
        post: operations["resendMfaCode"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rotar el refresh token y obtener un par nuevo
         * @description La rotación es obligatoria: el token presentado queda invalidado.
         *     Presentar un token ya rotado se interpreta como robo de credencial y
         *     revoca la familia de sesiones completa (RF-006).
         */
        post: operations["refreshSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revocar el refresh token de la sesión actual */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/password-reset/request": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Solicitar un enlace de restablecimiento
         * @description Responde `202` exista o no la cuenta, para no revelar qué correos están registrados.
         */
        post: operations["requestPasswordReset"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/password-reset/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Fijar una contraseña nueva con el token recibido */
        post: operations["confirmPasswordReset"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/oauth/authorize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Autorizar al cliente mediante Authorization Code con PKCE
         * @description Valida el cliente configurado, la coincidencia exacta de `redirect_uri`, `state`
         *     obligatorio y PKCE S256. Si existe la cookie SSO del Hub (`HttpOnly`, `Secure`,
         *     `SameSite=Lax`) no vuelve a pedir contraseña. Sin sesión SSO
         *     válida responde `302` al login del Hub con `continue` = la ruta relativa de esta misma
         *     petición; el login solo acepta `continue` si es una ruta relativa que empieza por
         *     `/oauth/authorize` (nunca una URL absoluta ni `//host`, para evitar redirección abierta)
         *     y vuelve a ella tras completar el MFA. Los errores con una URI validada se
         *     devuelven por redirección según RFC 6749 §4.1.2.1. No se habilita CORS aquí.
         *     Los parámetros en `snake_case` son nombres de protocolo definidos por RFC 6749.
         */
        get: operations["authorizeClient"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/oauth/token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Canjear un código de autorización por un access token
         * @description Acepta exclusivamente `application/x-www-form-urlencoded`. CORS se permite sin
         *     credenciales y solo para el origen configurado del cliente. No emite refresh token.
         *     Los campos en `snake_case` son nombres de protocolo definidos por RFC 6749.
         */
        post: operations["exchangeAuthorizationCode"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Perfil del usuario autenticado */
        get: operations["getCurrentUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Actualizar el perfil propio */
        patch: operations["updateCurrentUser"];
        trace?: never;
    };
    "/api/v1/me/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Sesiones activas del titular */
        get: operations["listSessions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/sessions/{sessionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Revocar una sesión concreta */
        delete: operations["revokeSession"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Listar y buscar cuentas */
        get: operations["listUsers"];
        put?: never;
        /** Dar de alta a un empleado y enviar su invitación */
        post: operations["createEmployee"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/users/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Consultar una cuenta */
        get: operations["getUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Cambiar el estado o los roles de una cuenta
         * @description Un administrador no puede deshabilitarse ni asignarse roles a sí mismo (invariantes 6 y 11).
         */
        patch: operations["updateUser"];
        trace?: never;
    };
    "/api/v1/admin/users/{userId}/invitation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Reenviar la invitación de una cuenta pendiente
         * @description Anula invitaciones anteriores y envía un enlace nuevo que vence en 24 horas.
         */
        post: operations["resendInvitation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/audit-log": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Consultar el registro de auditoría */
        get: operations["listAuditLog"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Error en formato RFC 7807. Nunca revela si un correo está registrado. */
        Problem: {
            /**
             * Format: uri
             * @example https://identity.local/problems/invalid-credentials
             */
            type: string;
            /** @example Credenciales inválidas */
            title: string;
            /** @example 401 */
            status: number;
            detail?: string;
            instance?: string;
            /** @description Detalle por campo en errores de validación */
            errors?: {
                field: string;
                message: string;
            }[];
        };
        HealthStatus: {
            /** @enum {string} */
            status: "ok";
            version: string;
        };
        ReadinessStatus: {
            /** @enum {string} */
            status: "ready" | "degraded";
            checks: {
                [key: string]: {
                    /** @enum {string} */
                    status: "up" | "down";
                    error?: string;
                };
            };
        };
        Jwks: {
            keys: {
                /** @example OKP */
                kty: string;
                /** @example Ed25519 */
                crv: string;
                /** @description Clave pública en base64url */
                x: string;
                kid: string;
                /** @example sig */
                use: string;
                /** @example EdDSA */
                alg: string;
            }[];
        };
        /** @enum {string} */
        UserStatus: "pending_verification" | "active" | "locked" | "disabled";
        /** @enum {string} */
        Role: "admin" | "user" | "contabilidad.senior" | "contabilidad.analista";
        User: {
            /** Format: uuid */
            id: string;
            /** Format: email */
            email: string;
            displayName: string;
            status: components["schemas"]["UserStatus"];
            roles: components["schemas"]["Role"][];
            /** @description Siempre verdadero para cuentas activas; no requiere enrolamiento */
            mfaEnabled: boolean;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            lastLoginAt?: string | null;
        };
        UserPage: {
            items: components["schemas"]["User"][];
            nextCursor?: string | null;
        };
        AdminCreateUserRequest: {
            /** Format: email */
            email: string;
            displayName: string;
            roles: components["schemas"]["Role"][];
        };
        InvitationAcceptRequest: components["schemas"]["TokenRequest"] & {
            /** Format: password */
            password: string;
        };
        LoginRequest: {
            /** Format: email */
            email: string;
            /** Format: password */
            password: string;
        };
        TokenPair: {
            /** @description JWT Ed25519 */
            accessToken: string;
            /** @enum {string} */
            tokenType: "Bearer";
            /**
             * @description Segundos de vigencia del access token
             * @example 900
             */
            expiresIn: number;
        };
        MfaChallenge: {
            /** @description Token de un solo uso, vigente 5 minutos */
            mfaToken: string;
            /** @example 300 */
            expiresIn: number;
        };
        MfaVerifyRequest: {
            mfaToken: string;
            /** @description Código de un solo uso enviado por correo */
            code: string;
        };
        MfaResendRequest: {
            mfaToken: string;
        };
        TokenRequest: {
            token: string;
        };
        EmailRequest: {
            /** Format: email */
            email: string;
        };
        PasswordResetConfirmRequest: {
            token: string;
            /** Format: password */
            password: string;
        };
        UpdateProfileRequest: {
            displayName?: string;
        };
        AdminUpdateUserRequest: {
            status?: components["schemas"]["UserStatus"];
            roles?: components["schemas"]["Role"][];
        };
        OAuthTokenRequest: {
            /** @enum {string} */
            grant_type: "authorization_code";
            code: string;
            /** Format: uri */
            redirect_uri: string;
            client_id: string;
            code_verifier: string;
        };
        OAuthTokenResponse: {
            /** @description JWT Ed25519 con `aud` del cliente y solo sus roles */
            access_token: string;
            /** @enum {string} */
            token_type: "Bearer";
            /** @example 900 */
            expires_in: number;
        };
        Session: {
            /** Format: uuid */
            id: string;
            ip: string;
            userAgent: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            lastUsedAt: string;
            /** @description Indica si es la sesión desde la que se consulta */
            current: boolean;
        };
        AuditEvent: {
            /** Format: int64 */
            id: number;
            /** Format: uuid */
            actorUserId?: string | null;
            /** @example login_failed */
            action: string;
            resourceType?: string | null;
            resourceId?: string | null;
            ip?: string | null;
            userAgent?: string | null;
            metadata?: {
                [key: string]: unknown;
            };
            /** Format: date-time */
            createdAt: string;
        };
        AuditLogPage: {
            items: components["schemas"]["AuditEvent"][];
            nextCursor?: string | null;
        };
    };
    responses: {
        /** @description Petición mal formada o que no supera la validación */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Credenciales ausentes, inválidas o expiradas */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Autenticado pero sin permiso para este recurso */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description El recurso no existe */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Límite de peticiones excedido */
        TooManyRequests: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: {
        UserId: string;
        SessionId: string;
        /** @description Búsqueda parcial por correo o nombre */
        Query: string;
        Status: components["schemas"]["UserStatus"];
        Action: string;
        ActorId: string;
        Since: string;
        Limit: number;
        Cursor: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description El proceso está vivo */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthStatus"];
                };
            };
        };
    };
    getReadiness: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Todas las dependencias responden */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadinessStatus"];
                };
            };
            /** @description Alguna dependencia no responde */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadinessStatus"];
                };
            };
        };
    };
    getJwks: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Conjunto de claves públicas */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Jwks"];
                };
            };
        };
    };
    acceptInvitation: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InvitationAcceptRequest"];
            };
        };
        responses: {
            /** @description Invitación aceptada y cuenta activada */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            /** @description El token expiró o ya fue usado */
            410: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Se requiere segundo factor */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MfaChallenge"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            /** @description Cuenta bloqueada por intentos fallidos */
            423: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description Límite de peticiones excedido, o ya se emitieron 5 desafíos MFA para la cuenta en 15 minutos */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            /** @description No se pudo enviar el código MFA; el desafío se anula y no consume el límite de emisión */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    verifyMfa: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MfaVerifyRequest"];
            };
        };
        responses: {
            /** @description Sesión iniciada. Emite dos cookies independientes: el refresh de la consola (`SameSite=Strict`, ADR 0005) y la sesión SSO del Hub (`SameSite=Lax`, ADR 0009), que usa `/oauth/authorize` para no volver a pedir credenciales. */
            200: {
                headers: {
                    /** @description 'refresh_token=<opaco>; HttpOnly; Secure; SameSite=Strict; Path=/api/v1/auth; Max-Age=<vigencia del refresh>' y, en otra cabecera Set-Cookie, 'hub_session=<opaco>; HttpOnly; Secure; SameSite=Lax; Path=/oauth; Max-Age=<vigencia de la sesión SSO>' */
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPair"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    resendMfaCode: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MfaResendRequest"];
            };
        };
        responses: {
            /** @description Código anterior anulado y nuevo envío encolado */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            429: components["responses"]["TooManyRequests"];
            /** @description No se pudo enviar el código MFA; se restaura el código anterior y el reintento no espera 60 segundos */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    refreshSession: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie: {
                /** @description Refresh token opaco de la sesión actual. */
                refresh_token: string;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Par de tokens renovado */
            200: {
                headers: {
                    /** @description refresh_token=<opaco>; HttpOnly; Secure; SameSite=Strict; Path=/api/v1/auth; Max-Age=<vigencia del refresh> */
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPair"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie: {
                /** @description Refresh token opaco de la sesión actual. */
                refresh_token: string;
            };
        };
        requestBody?: never;
        responses: {
            /** @description Sesión cerrada */
            204: {
                headers: {
                    /** @description refresh_token=; HttpOnly; Secure; SameSite=Strict; Path=/api/v1/auth; Max-Age=0 */
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    requestPasswordReset: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EmailRequest"];
            };
        };
        responses: {
            /** @description Si la cuenta existe, se envió el correo */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            429: components["responses"]["TooManyRequests"];
            /** @description El servicio de restablecimiento no está disponible */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    confirmPasswordReset: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordResetConfirmRequest"];
            };
        };
        responses: {
            /** @description Contraseña actualizada y sesiones revocadas; el aviso por correo se publica tras confirmar y un fallo del broker no cambia el resultado (D16) */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            400: components["responses"]["BadRequest"];
            /** @description El token expiró o ya fue usado */
            410: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    authorizeClient: {
        parameters: {
            query: {
                client_id: string;
                redirect_uri: string;
                response_type: "code";
                state: string;
                code_challenge: string;
                code_challenge_method: "S256";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Redirección al cliente con `code` y `state`, o con `error` y el mismo `state`. */
            302: {
                headers: {
                    Location: string;
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Petición inválida que no puede redirigirse de forma segura. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    exchangeAuthorizationCode: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/x-www-form-urlencoded": components["schemas"]["OAuthTokenRequest"];
            };
        };
        responses: {
            /** @description Access token dirigido al cliente */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OAuthTokenResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
        };
    };
    getCurrentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Perfil */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    updateCurrentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProfileRequest"];
            };
        };
        responses: {
            /** @description Perfil actualizado */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
        };
    };
    listSessions: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Listado de sesiones */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"][];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    revokeSession: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sessionId: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Sesión revocada */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    listUsers: {
        parameters: {
            query?: {
                /** @description Búsqueda parcial por correo o nombre */
                q?: components["parameters"]["Query"];
                status?: components["parameters"]["Status"];
                limit?: components["parameters"]["Limit"];
                cursor?: components["parameters"]["Cursor"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Página de cuentas */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserPage"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    createEmployee: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminCreateUserRequest"];
            };
        };
        responses: {
            /** @description Cuenta creada en estado pending_verification */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            /** @description El correo ya está registrado */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    getUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: components["parameters"]["UserId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cuenta */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    updateUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: components["parameters"]["UserId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AdminUpdateUserRequest"];
            };
        };
        responses: {
            /** @description Cuenta actualizada */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
        };
    };
    resendInvitation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                userId: components["parameters"]["UserId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Invitación reenviada */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            /** @description La cuenta no está pendiente de verificación */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
        };
    };
    listAuditLog: {
        parameters: {
            query?: {
                action?: components["parameters"]["Action"];
                actorId?: components["parameters"]["ActorId"];
                since?: components["parameters"]["Since"];
                limit?: components["parameters"]["Limit"];
                cursor?: components["parameters"]["Cursor"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Página de eventos */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditLogPage"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
}
